# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snippy < Formula
  desc "A rich terminal user interface (TUI) for Snipo - your self-hosted snippet manager."
  homepage "https://github.com/MohamedElashri/snipo"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MohamedElashri/snipo/releases/download/snippy-v0.1.0/snippy_Darwin_x86_64.tar.gz"
      sha256 "d95c1429e4cda11ea707447f990faad99b8548ccb8f24f63c2df59b00daba313"

      define_method(:install) do
        bin.install "snippy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MohamedElashri/snipo/releases/download/snippy-v0.1.0/snippy_Darwin_arm64.tar.gz"
      sha256 "d25839126dceaf048f36ca7a831a9e16a7c8b6136a3910339543efc68a3d43dc"

      define_method(:install) do
        bin.install "snippy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/snipo/releases/download/snippy-v0.1.0/snippy_Linux_x86_64.tar.gz"
      sha256 "0298cb314cf2688592d547748bcc3997ec5ee518b6dc25624714999235c07bbd"
      define_method(:install) do
        bin.install "snippy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/snipo/releases/download/snippy-v0.1.0/snippy_Linux_arm64.tar.gz"
      sha256 "567746c5c9c85cd228d49fccc9818f6764ec1c89079b8a1f88ae28848e280751"
      define_method(:install) do
        bin.install "snippy"
      end
    end
  end

  test do
    system "#{bin}/snippy version"
  end
end
